task: "ip_adapter"
sub_task: "image_variation"
experiment_name: ""

# Model Configs
personalized_model: "/path/to/model"
model_type: "sd1.5"
ip_adapter_model: "/path/to/model"
ip_adapter_weight_name: "face"
ip_adapter_scale: 0.7
res_adapter_model: "/path/to/model"
res_adapter_alpha: 1.0

# Inference Configs
width: 672
height: 864
scale_ratio: null  # scale the original image

num_inference_steps: 50
guidance_scale: 7.5
num_images_per_prompt: 4

ip_adapter_images: [
  "assets/ip_adapter/ai_face2.png",
]

prompts: [
  "A photo of a girl wearing a black dress, holding red roses in hand, upper body, behind is the Eiffel Tower",
]

n_prompt: "monochrome, lowres, bad anatomy, worst quality, low quality"

# Other Configs
enable_xformers: false  # Must false for ip-adapter, otherwise error occurs...
enable_compare: true
draw_text: false
seed: 40
device: 0
split_images: true