task: "t2i"
experiment_name: ""

# Model Configs
personalized_model: "/path/to/model"
model_type: "sdxl"
res_adapter_model: "/path/to/model"
res_adapter_alpha: 1.0

# Inference Configs
width: 512
height: 512
scale_ratio: null
num_inference_steps: 30
guidance_scale: 7.5
num_images_per_prompt: 2

prompts: [
  "(masterpiece), (extremely intricate), (realistic), portrait of a girl, the most beautiful in the world, (medieval armor), metal reflections, upper body, outdoors, intense sunlight, far away castle, professional photograph of a stunning woman detailed, sharp focus, dramatic, award winning, cinematic lighting, octane render unreal engine, volumetrics dtx, (film grain, blurry background, blurry foreground, bokeh, depth of field, sunset, motion blur), chainmail",
  "Portrait photo of muscular bearded guy in a worn mech suit, ((light bokeh)), intricate, (steel metal [rust]), elegant, sharp focus, photo by greg rutkowski, soft lighting, vibrant colors, (masterpiece), ((streets)), (detailed face), (glowing blue eyes)",
  "masterpiece, best quality, 1girl, sci-fi armor with black and red colors, glowing elements, redhair",
  "In Casey Baugh's evocative style, a Gothic girl emerges from the depths of darkness, her essence a captivating blend of mystery and allure. With piercing eyes and flowing ebony hair, she exudes an enigmatic presence that draws viewers into her world. Baugh's brushwork infuses the painting with a unique combination of realism and abstraction, highlighting the girl's delicate features and contrasting them against a backdrop of deep, rich hues. The interplay of light and shadow adds depth and dimension to the artwork, creating a hauntingly beautiful portrayal of this Gothic muse. Baugh's distinctive style captures the essence of the girl's enigmatic nature, inviting viewers to explore the depths of her soul. Signature",
]

n_prompt: "ugly, deformed, noisy, blurry, low contrast, text, BadDream, 3d, cgi, render, fake, anime, open mouth, big forehead, long neck"

# Other Configs
enable_xformers: true
enable_compare: true
draw_text: true
seed: 42
device: 0
split_images: false